set relativenumber
set hidden
set tabstop=2 softtabstop=2
set shiftwidth=2
set expandtab
set smartindent
set number
set nowrap
set noswapfile
set undofile
set incsearch
set nohlsearch
set termguicolors
set scrolloff=8
set signcolumn=auto
set colorcolumn=80
set background=dark
set switchbuf+=useopen
set guicursor=
set nofoldenable
set shortmess-=F
set smartcase
set ignorecase
set completeopt=menuone,noinsert,noselect
